@echo off
echo Run as admin before to go thru
pause
echo Creating 100 users
echo Creating 100 users
net user /add User
net user /add User2
net user /add User3
net user /add User4
net user /add User5
net user /add User6
net user /add User7
net user /add User8
net user /add User9
net user /add User10
net user /add User11
net user /add User12
net user /add User13
net user /add User14
net user /add User15
net user /add User16
net user /add User17
net user /add User18
net user /add User19
net user /add User20
net user /add User21
net user /add User22
net user /add User23
net user /add User24
net user /add User25
net user /add User26
net user /add User27
net user /add User28
net user /add User29
net user /add User30
net user /add User31
net user /add User32
net user /add User33
net user /add User34
net user /add User35
net user /add User36
net user /add User37
net user /add User38
net user /add User39
net user /add User40
net user /add User41
net user /add User42
net user /add User43
net user /add User44
net user /add User45
net user /add User46
net user /add User47
net user /add User48
net user /add User49
net user /add User50
net user /add User51
net user /add User52
net user /add User53
net user /add User54
net user /add User55
net user /add User56
net user /add User57
net user /add User58
net user /add User59
net user /add User60
net user /add User61
net user /add User62
net user /add User63
net user /add User64
net user /add User65
net user /add User66
net user /add User67
net user /add User68
net user /add User69
net user /add User70
net user /add User71
net user /add User72
net user /add User73
net user /add User74
net user /add User75
net user /add User76
net user /add User77
net user /add User78
net user /add User79
net user /add User80
net user /add User81
net user /add User82
net user /add User83
net user /add User84
net user /add User85
net user /add User86
net user /add User87
net user /add User88
net user /add User89
net user /add User90
net user /add User91
net user /add User92
net user /add User93
net user /add User94
net user /add User95
net user /add User96
net user /add User97
net user /add User98
net user /add User99
net user /add User100